# .github/workflows/publish.yml

name: Publish

on:  
  # Run on push or PRs to master
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Allows reading of the repository's contents.
      id-token: write # Allows the creation of an ID token for authentication with JSR.

    services:
      rabbitmq:
        image: rabbitmq:3-management
        ports:
          - 5672:5672   # AMQP port
          - 15672:15672 # dashboard management 
        options: >-
          --health-cmd "rabbitmq-diagnostics -q ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x

      - name: Wait for RabbitMQ
        run: |
          echo "Waiting RabbitMQ..."
          for i in {1..10}; do
            if nc -z localhost 5672; then
              echo "RabbitMQ is ready"
              break
            fi
            echo "RabbitMQ not ready..."
            sleep 3
          done
        
      - name: Run tests
        run: deno test --allow-all

      - name: Publish to Deno
        run: deno publish
